{% set name = "aiorwlock" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiorwlock-{{ version }}.tar.gz
  sha256: 4cea5bec4e9d03533a26919299394822a1422aa519bca9dd09178ec490f8d1cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - aiorwlock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiorwlock
  summary: Read write lock for asyncio.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wendazhou
